spring.application.name=duermechill
# Puerto donde correrá el servidor
server.port=8080
server.address=0.0.0.0


# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/duermechill_db?serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Permitir inicializar esquema SQL con Spring Boot
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Configuración de zona horaria para Jackson (JSON serialization)
spring.jackson.time-zone=Europe/Madrid
spring.jackson.default-property-inclusion=non_empty